language: r
sudo: required

apt_packages:
  - gdal-bin
  - libgdal-dev
  - libgdal1-dev
  - netcdf-bin
  - libproj-dev
  - libgdal1h

r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e 'library(covr);coveralls()'

env:
  - warnings_are_errors: true
